# Builder stage
# Use Rust v1.63 stable release as base image
FROM rust:1.63.0 as builder
# Set workdir to 'app
WORKDIR /app
# Install system dependencies
RUN apt update && apt install lld clang -y
# Copy project files
COPY . .
# Make sqlx look at saved metadata
ENV SQLX_OFFLINE true
# Build the binary in release mode
RUN cargo build --release

# Runtime stage
FROM debian:bullseye-slim AS runtime

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/zero2prod zero2prod

COPY configuration configuration
# Set app environment
ENV APP_ENVIRONMENT production

# Set entrypoing
ENTRYPOINT ["./zero2prod"]
