application: 
  port: 8000
  hmac_secret: "118a31050-afef-4119-8573-e64b5584bedc-8a31050-afef-4119-8573-e64b5584bedc"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: my-secret-token
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
